#!/bin/sh
#SBATCH -N 1
#SBATCH -n 40

#Default web submit job template
echo Webrip job $PROJECT $INDEX $RESO $LANGG $CODEC $MODE
echo running on $HOSTNAME at $PWD
. ${ENCROOT}/init.sh

srun -n 1 webencode.sh -n $PROJECT -i $INDEX -r $RESO -l $LANGG -c $CODEC -m $MODE
