#!/bin/sh
#SBATCH -N 1

#Default web submit job template
echo Webrip job $PROJECT $INDEX $RESO $LANGG $CODEC $MODE
echo running on $HOSTNAME at $PWD
. ${ENCROOT}/init.sh

[ -n "$MODE" ] && MODE="-m $MODE"
[ -n "$PROFILE" ] && MODE="-p $PROFILE"

srun -n 1 --cpu-bind=sockets webencode.sh -n $PROJECT -i $INDEX -r $RESO -l $LANGG -c $CODEC $MODE $PROFILE
